---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name:  daloradius-cert
  namespace: ittlabb
spec:
  dnsNames:
    - daloradius.ittlabb.net
  secretName: daloradius-cert-tls
  issuerRef:
    name: ca-issuer
