---
apiVersion: v1
kind: Secret
metadata:
  name: oauth-proxy-secret
  namespace: default
data:
  github-client-id: app_id_in_base64
  github-client-secret: client_secret_in_base64
  cookie-secret: cookie_in_base4 
