apiVersion: v1
kind: Service
metadata:
  name: freeradius
spec:
  type: LoadBalancer
  ports:
    - name: radius
      port: 1812
      protocol: UDP
      targetPort: 1812
    - name: radius-acct
      port: 1813
      protocol: UDP
      targetPort: 1813
  selector:
    app: freeradius
