---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name:  plex-cert
  namespace: ittlabb
spec:
  dnsNames:
    - plex.ittlabb.net
  secretName: plex-cert-tls
  issuerRef:
    name: ca-issuer
