---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name:  oxidized-cert
  namespace: ittlabb
spec:
  dnsNames:
    - oxidized.ittlabb.net
  secretName: oxidized-cert-tls
  issuerRef:
    name: ca-issuer
