---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name:  dokuwiki-cert
  namespace: ittlabb
spec:
  dnsNames:
    - dokuwiki.ittlabb.net
  secretName: dokuwiki-cert-tls
  issuerRef:
    name: ca-issuer
