apiVersion: v1
kind: Service
metadata:
  name: minecraft-spigot
spec:
  type: LoadBalancer
  ports:
    - name: minecraft
      port: 25565
      protocol: TCP
      targetPort: 25565
    - name: dynmap
      port: 8123
      protocol: TCP
      targetPort: 8123
  selector:
    app: minecraft-spigot
