apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freeradius-daloradius-pv-claim
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Mi
