---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name:  freeradius-cert
  namespace: ittlabb
spec:
  dnsNames:
    - freeradius.ittlabb.net
  secretName: freeradius-cert-tls
  issuerRef:
    name: ca-issuer
