---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name:  dn-wordpress-cert
  namespace: ittlabb
spec:
  dnsNames:
    - dn-wordpress.ittlabb.net
  secretName: dn-wordpress-cert-tls
  issuerRef:
    name: ca-issuer
